apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.host }}
  namespace: ziinc-copilot
spec:
  dnsNames:
  - {{ .Values.ingress.host }}
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-webhook-dnsimple-staging
  secretName: ziinc-tls
