apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziinc-copilot
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ziinc-copilot
  template:
    metadata:
      labels:
        app: ziinc-copilot
    spec:
      containers:
      - name: ziinc-copilot
        image: your-docker-registry/ziinc-copilot:latest
        ports:
        - containerPort: 8080
        env:
        - name: HOST
          value: "https://ziinc.dev"
        - name: PORT
          value: "8080"
