apiVersion: apps/v1
kind: Deployment
metadata:
  name: ziinc-copilot
  namespace: ziinc-copilot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ziinc-copilot
  template:
    metadata:
      labels:
        app: ziinc-copilot
    spec:
      containers:
      - name: ziinc-copilot
        image: {{ .Values.image.repositroy }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: HOST
          value: "https://{{ .Values.ingress.host }}/"
        - name: PORT
          value: "8080"
        envFrom:
        - configMapRef:
            name: ziinc-copilot
        - secretRef:
            name: ziinc-copilot
