apiVersion: v1
kind: Service
metadata:
  name: ziinc-copilot
  namespace: ziinc-copilot
spec:
  selector:
    app: ziinc-copilot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
